#!/usr/bin/with-contenv bash

# Copy default config if not found
if [ ! -f "/config/my.cnf" ]; then
	cp /etc/default/my.cnf /config/my.cnf
fi

if [ ! -d "/var/lib/mysql" ]; then
	/usr/bin/mysql_install_db --user=mysql
fi